export const environment = {
  production: true,
  loginServer: 'https://cocon2.tedsys.in/cocon-counter-version/public',
  appKey:'ABCD0001',
  endpoints:{
    eventDetails:{api:'api/fetch-active-event',method:'get',authenticationType:'appkey'},
    login: {api:'api/login-with-otp',method:'post',authenticationType:'appkey'},
    verifyOtp: {api:'api/verify-otp',method:'post',authenticationType:'appkey'},
    delegateprofile:{api:'api/delegate/profile',method:'get',authenticationType:'OAuth'},
    delegateBadge:{api:'api/delegate/virtual-badge',method:'get',authenticationType:'OAuth'},
    networkingDelegates:{api:'api/networking-delegates',method:'get',authenticationType:'OAuth'},
    networkingStatusUpdated:{api:'api/update-networking-status',method:'post',authenticationType:'OAuth'},
    addChatRequest:{api:'api/store-chat-request',method:'post',authenticationType:'OAuth'},
    updateChatRequest:{api:'api/update-chat-request',method:'post',authenticationType:'OAuth'},
    fetchChatMessages:{api:'api/fetch-chat-messages',method:'get',authenticationType:'OAuth'},
    addChatMessage:{api:'api/store-chat-message',method:'post',authenticationType:'OAuth'},
    schedules: {api:'api/schedules',method:'get',authenticationType:'appkey'},
    todaySchedule:{api:'api/today-schedules',method:'get',authenticationType:'appkey'},
    participants: {api:'api/participants',method:'get',authenticationType:'appkey'},
    sponserWithCategoriesAndList: { api: 'api/category-wise-sponsors', method: 'get', authenticationType: 'appkey' },
    feedbackQuestionList:{api:'api/feedback-questions',method:'get',authenticationType:'OAuth'},
    feedbackSubmit:{api:'api/store_delegate_feedback',method:'post',authenticationType:'OAuth'},
    exhibitorsList:{api:'api/exhibitors',method:'get',authenticationType:'appkey'},
    directorywithCategoriesAndList: { api: 'api/category-wise-directories', method: 'get', authenticationType: 'appkey' },
    attractionWithCategoryAndList:{api:'api/category-wise-attractions',method:'get',authenticationType:'appkey'},
    fcmToken: { api: 'api/update-phone-identifier', method: 'post', authenticationType: 'OAuth' },
    appHelp: { api: 'api/fetch-app-help', method: 'get', authenticationType: 'appkey' },
    aboutConference: { api: 'api/fetch-about-conference', method: 'get', authenticationType: 'appkey' },
  
  }
};
